### ISSUE TITLE
Is this driver for linux system?

### ISSUE THREAD

**Issue by braveheart007** [gswly/sensor-imu#1]
Is this driver for linux system? Linux head file refered in driver. I wonder how to use this driver with RTOS.

**Comment by aler9** [comment]
Hello, this isn't a driver, and as driver i mean something that runs in kernel space,  it's a simple user space C library for interacting with Invensense IMUs, that i use a lot when i want to find out whether a IMU works, or to see how much well a orientation estimation algorithm performs in the real world.

When we want to interface I2C-based sensors, like these kind of IMUs, to both RTOS and Linux, generally the driver is included in the OS and provides functions for sending and receiving generic data via I2C, while the user-space software calls these functions and gives meaning to the data. This library provides the latter functionality.

And yes, this is for Linux, but it shouldn't be difficult to adapt it for any RTOS or microcontroller, it's enough to replace the functions that allows to read/write via I2C with the ones provided by your OS.

**Comment by braveheart007** [comment]
Thanks for your detailed explanation about driver, absolutely agree!
Both Linux and motion sensors are kind of unfamiliar for me right now. But your repository attractted me for further study of those things. What I am doing is try to adapt these program with RTOS.
