### ISSUE TITLE
uninitialize problem

### ISSUE THREAD

**Issue by jasonxuzh** [gswly/sensor-imu#2]
When calculate acc align matrix and gyro bias, temp var should be initialized, or it lead to get "nan" value

**Comment by aler9** [comment]
Hello, sorry if i didn't provided any examples, this is a library i wrote for viewing orientations in 3D on a Raspberry Pi (https://github.com/aler9/raspberry-imu-viewer), and after i finished the project i switched to another work.

Anyway, you can find in the raspberry-imu-viewer repository a working example on how to use the align_dcm and gyro_bias structs:
https://github.com/aler9/raspberry-imu-viewer/blob/master/main.c

and now that i think of it, neither of them have a "temp" value, are you sure they're what you're looking for?
